# Generated by Django 6.0 on 2025-12-15 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другое')], default='O', max_length=1, verbose_name='Пол')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP клиент')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClothesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тип одежды',
                'verbose_name_plural': 'Типы одежды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('category', models.CharField(choices=[('top', 'Верхняя одежда'), ('bottom', 'Нижняя одежда'), ('dress', 'Платья и юбки'), ('underwear', 'Белье'), ('accessories', 'Аксессуары')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('clothes_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assortments', to='firstapp_var_11.clothestype', verbose_name='Тип одежды')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Ассортимент',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма покупки')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('online', 'Онлайн оплата')], default='card', max_length=20, verbose_name='Способ оплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='firstapp_var_11.buyer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='firstapp_var_11.seller', verbose_name='Продавец')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Стаж (лет)')),
                ('department', models.CharField(max_length=100, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Профиль продавца',
                'verbose_name_plural': 'Профили продавцов',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.CharField(max_length=10, verbose_name='Значение размера')),
                ('system', models.CharField(choices=[('int', 'Международный (XS-XXL)'), ('ru', 'Российский (42-56)'), ('eu', 'Европейский (36-50)'), ('us', 'Американский (2-20)')], default='int', max_length=3, verbose_name='Система размеров')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'unique_together': {('size_value', 'system')},
            },
        ),
        migrations.CreateModel(
            name='AssortmentSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество в наличии')),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp_var_11.assortment', verbose_name='Товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp_var_11.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Наличие по размеру',
                'verbose_name_plural': 'Наличие по размерам',
                'unique_together': {('assortment', 'size')},
            },
        ),
        migrations.AddField(
            model_name='assortment',
            name='available_sizes',
            field=models.ManyToManyField(through='firstapp_var_11.AssortmentSize', to='firstapp_var_11.size', verbose_name='Доступные размеры'),
        ),
    ]
